feat!: Update to Uno 5
nventive/Nventive.Persistence pull request #56
Opened 2023-12-21 16:13 UTC by juliecantin

GitHub Issue: #

## Proposed Changes

Feature

## What is the current behavior?

Nventive.Persistence targets Uno 4 and .net 6

## What is the new behavior?

Nventive.Persistence targets Uno 5 and .net 7

## Checklist

Please check if your PR fulfills the following requirements:

- [x] Documentation has been added/updated
- [ ] Automated Unit / Integration tests for the changes have been added/updated
- [ ]  ~~Contains **NO** breaking changes~~
- [x] Updated the Changelog
- [ ] Associated with an issue

Apps will need to [migrate to Uno 5](https://platform.uno/docs/articles/migrating-to-uno-5.html).

## Other information

2023-12-21 17:58 UTC, jeanplevesque approved these changes

2023-12-21 18:26 UTC, jeanplevesque requested changes

2023-12-21 18:26 UTC, jeanplevesque commented on src/Persistence.Uno.WinUI/Persistence.Uno.WinUI.csproj
> -	<PropertyGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
Keep WASM.

2023-12-23 19:34 UTC, jeanplevesque requested changes

2023-12-23 19:34 UTC, jeanplevesque commented on build/gitversion.yml
> +next-version: 1.0.0
This package is still in pre-release. The `next-version` should be 0.5.0

2024-01-03 18:40 UTC, CBrunet2212 approved these changes

2024-01-03 18:47 UTC, carlh98 approved these changes

2024-01-08 13:19 UTC, Soap-141 approved these changes

2024-01-08 14:29 UTC, juliecantin commented
@jeanplevesque We've implemented the changes you've requested, is the PR good to go?

2024-01-08 14:31 UTC, carlh98 commented
@juliecantin JP should be back tomorrow :)

2024-01-09 13:15 UTC, jeanplevesque approved these changes

2024-01-09 13:55 UTC, merged